"""Deterministic discovery, metadata, and original-file identities."""

from __future__ import annotations

import hashlib
import logging
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_LOGGER = logging.getLogger(__name__)

RAW_EXTENSIONS = frozenset(
    {
        ".arw",
        ".srf",
        ".sr2",
        ".crw",
        ".cr2",
        ".cr3",
        ".nef",
        ".nrw",
        ".orf",
        ".rw2",
        ".raf",
        ".pef",
        ".ptx",
        ".dng",
        ".rwl",
        ".3fr",
        ".fff",
        ".iiq",
        ".kdc",
        ".dcr",
        ".mos",
        ".mrw",
        ".erf",
        ".srw",
        ".raw",
    }
)
IMAGE_EXTENSIONS = RAW_EXTENSIONS | {
    ".jpg",
    ".jpeg",
    ".jpe",
    ".png",
    ".tif",
    ".tiff",
    ".webp",
    ".heic",
    ".heif",
    ".avif",
    ".bmp",
}
# These directories are generated by this application or the old analyzer.
# Generic user folder names (e.g. "previews") are deliberately not excluded.
PRODUCT_DIRECTORIES = {
    ".photo-select",
    ".photo-select-cache",
    "photo-select-cache",
    "photoselect-cache",
    "analysis_output",
    "analysis_results",
    "culling_output",
    "__pycache__",
    ".git",
}


@dataclass(frozen=True)
class SourceIdentity:
    path: Path
    photo_id: str
    size: int
    mtime_ns: int
    cache_key: str


def source_identity(path: Path, *, config_version: str) -> SourceIdentity:
    resolved = path.resolve(strict=True)
    normalized = os.path.normcase(str(resolved))
    stat = resolved.stat()
    photo_id = hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:24]
    identity = f"{normalized}\0{stat.st_size}\0{stat.st_mtime_ns}\0{config_version}"
    cache_key = hashlib.sha256(identity.encode("utf-8")).hexdigest()
    return SourceIdentity(resolved, photo_id, stat.st_size, stat.st_mtime_ns, cache_key)


def discover_images(source: Path, cache: Path) -> list[Path]:
    """Walk recursively without symlink loops or ingesting our own cache."""
    source = source.resolve(strict=True)
    cache = cache.resolve()
    if not source.is_dir():
        raise ValueError(f"Source is not a directory: {source}")
    if source == cache or source.is_relative_to(cache):
        raise ValueError("Source directory must not be inside the preview cache")
    legacy_analysis = source / "analysis"
    has_legacy_outputs = any(
        (legacy_analysis / marker).is_file()
        for marker in ("analysis.json", "report.html", "decisions.json")
    )
    legacy_directories = (
        {source / name for name in ("analysis", "output", "previews")}
        if has_legacy_outputs
        else set()
    )
    found: list[Path] = []
    for directory, names, files in os.walk(source, followlinks=False):
        base = Path(directory)
        names[:] = sorted(
            name
            for name in names
            if name.casefold() not in PRODUCT_DIRECTORIES
            and not (base / name).is_symlink()
            and (base / name) not in legacy_directories
            and not (base / name).resolve().is_relative_to(cache)
        )
        for name in sorted(files):
            path = base / name
            if path.suffix.lower() not in IMAGE_EXTENSIONS or path.is_symlink():
                continue
            if path.resolve().is_relative_to(cache):
                continue
            found.append(path)
    return sorted(found, key=lambda item: os.path.normcase(str(item)))


def read_metadata(path: Path) -> dict[str, Any]:
    """Read EXIF cheaply; missing or damaged EXIF never prevents decoding."""
    tags: dict[str, Any] = {}
    if path.suffix.lower() in RAW_EXTENSIONS | {
        ".jpg",
        ".jpeg",
        ".jpe",
        ".tif",
        ".tiff",
    }:
        try:
            import exifread

            with path.open("rb") as stream:
                tags = exifread.process_file(stream, details=False, strict=False)
        except Exception:
            _LOGGER.debug("EXIF metadata unavailable for %s", path, exc_info=True)
    # Pillow also reads EXIF from PNG, WebP and HEIF, which ExifRead may not.
    if path.suffix.lower() not in RAW_EXTENSIONS:
        try:
            from PIL import Image

            with Image.open(path) as image:
                exif = image.getexif()
                image_fields = {
                    271: "Image Make",
                    272: "Image Model",
                    274: "Image Orientation",
                    306: "Image DateTime",
                }
                exif_fields = {
                    36867: "EXIF DateTimeOriginal",
                    36868: "EXIF DateTimeDigitized",
                    37520: "EXIF SubSecTime",
                    37521: "EXIF SubSecTimeOriginal",
                    37522: "EXIF SubSecTimeDigitized",
                    36880: "EXIF OffsetTime",
                    36881: "EXIF OffsetTimeOriginal",
                    36882: "EXIF OffsetTimeDigitized",
                }
                for number, name in image_fields.items():
                    if number in exif:
                        tags.setdefault(name, exif[number])
                nested = exif.get_ifd(34665)
                for number, name in exif_fields.items():
                    value = nested.get(number, exif.get(number))
                    if value is not None:
                        tags.setdefault(name, value)
        except Exception:
            _LOGGER.debug("Pillow metadata unavailable for %s", path, exc_info=True)
    return tags


def tag_text(tags: dict[str, Any], *names: str) -> str | None:
    for name in names:
        value = tags.get(name)
        if value is not None and str(value).strip():
            return str(value).strip().strip("\x00")
    return None


def orientation_from_tags(tags: dict[str, Any]) -> int | None:
    tag = tags.get("Image Orientation")
    if isinstance(tag, int):
        return tag if 1 <= tag <= 8 else None
    values = getattr(tag, "values", None)
    if values:
        try:
            value = int(values[0])
            return value if 1 <= value <= 8 else None
        except (ValueError, TypeError):
            pass
    return None


def camera_name(tags: dict[str, Any]) -> str | None:
    make = tag_text(tags, "Image Make")
    model = tag_text(tags, "Image Model")
    if model and make and not model.lower().startswith(make.lower()):
        return f"{make} {model}"
    return model or make


def capture_time(tags: dict[str, Any], path: Path) -> str:
    """Retain unknown camera time zones rather than inventing an offset."""
    fields = (
        ("EXIF DateTimeOriginal", "EXIF SubSecTimeOriginal", "EXIF OffsetTimeOriginal"),
        (
            "EXIF DateTimeDigitized",
            "EXIF SubSecTimeDigitized",
            "EXIF OffsetTimeDigitized",
        ),
        ("Image DateTime", "EXIF SubSecTime", "EXIF OffsetTime"),
    )
    for timestamp_tag, subsecond_tag, offset_tag in fields:
        value = tag_text(tags, timestamp_tag)
        if not value:
            continue
        try:
            # EXIF camera wall clocks have no zone unless an OffsetTime tag exists.
            moment = datetime.strptime(value[:19], "%Y:%m:%d %H:%M:%S")  # noqa: DTZ007
            fraction = tag_text(tags, subsecond_tag)
            if fraction and fraction.isdigit():
                moment = moment.replace(microsecond=int((fraction + "000000")[:6]))
            offset = tag_text(tags, offset_tag)
            if offset:
                moment = datetime.fromisoformat(moment.isoformat() + offset)
                moment = moment.astimezone(timezone.utc)
            return moment.isoformat().replace("+00:00", "Z")
        except (ValueError, OverflowError):
            continue
    return (
        datetime.fromtimestamp(path.stat().st_mtime, timezone.utc)
        .isoformat()
        .replace("+00:00", "Z")
    )
